FROM ubuntu:18.04
# enter your username here for x11 forwarding to work without 
# using the unsecure 'xhost +' method
ARG USERNAME
RUN groupadd -g 1000 ${USERNAME} && \
    useradd -d /home/${USERNAME} -s /bin/bash -m ${USERNAME} -u 1000 -g 1000

# set timezone otherwise cmake install will ask for it
ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ=America/San_Francisco
RUN ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
RUN echo "$TZ" > /etc/timezone
RUN apt-get update && \
    apt-get install -y tzdata

# install build tools and fix certificates so git pull works
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        python3 \
        python3-dev \
        # python-is-python3 \
        # python-dev-is-python3 \
        git \
        wget \
        cmake \
        emacs \
        vim \
        libssl-dev \
        openssl \
        build-essential &&\
    apt-get install --reinstall -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# install geant4 prerequisites
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev \
    libxft-dev libxext-dev libxmu-dev python \
    gfortran libssl-dev libpcre3-dev \
    xlibmesa-glu-dev libglew1.5-dev libftgl-dev \
    libmysqlclient-dev libfftw3-dev libcfitsio-dev \
    graphviz-dev libavahi-compat-libdnssd-dev \
    libldap2-dev python-dev libxml2-dev libkrb5-dev \
    libgsl0-dev libqt5opengl5-dev qt5-default libxerces-c-dev \
    python3-dev python3-numpy-dev unzip && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir tools
WORKDIR /tools

# download and install geant4 10.5.1
RUN wget https://gitlab.cern.ch/geant4/geant4/-/archive/v10.5.1/geant4-v10.5.1.zip && \
    unzip geant4-v10.5.1.zip && \
    rm geant4-v10.5.1.zip && \
    mkdir geant4-build-10

RUN cd geant4-build-10 && \
    cmake -DGEANT4_USE_OPENGL_X11=ON \
        -DGEANT4_USE_QT=ON \
        -DGEANT4_INSTALL_DATA=ON \
        -DGEANT4_INSTALL_DATADIR=tools/geant4-data \
        -DGEANT4_BUILD_MULTITHREADED=ON \
        -DGEANT4_USE_GDML=ON \
        -DGEANT4_INSTALL_EXAMPLES=ON \
        # -DG4INTY_USE_XT=ON \
        # -DG4VIS_USE_OPENGLX=ON \
        # -DG4UI_USE_TCSH=ON \
        # -DG4INTY_USE_QT=ON \
        # -DG4UI_USE_QT=ON \
        # -DG4VIS_USE_OPENGLQT=ON \
        # -DG4VIS_USE_OPENGLX=ON \
        -QT_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5 \
        -Qt5Core_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5Core \
        -Qt5Gui_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui \
        -Qt5OpenGL_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL \
        -Qt5PrintSupport_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5PrintSupport \
        -Qt5Widgets_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets \
        -Qt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5 \
        ../geant4-v10.5.1 && \
    make -j`nproc`

# install ROOT prerequisites
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev \
    libxft-dev libxext-dev python libssl-dev openssl mesa-common-dev && \
    rm -rf /var/lib/apt/lists/*

## Update CMake
RUN wget http://www.cmake.org/files/v3.27/cmake-3.27.0.tar.gz && \
    tar -xzvf cmake-3.27.0.tar.gz && \
    cd cmake-3.27.0 && \
    ./bootstrap && \
    make -j`nproc` && \
    make install

# download and build ROOT from source
RUN git clone --branch v6-24-00 --depth=1 https://github.com/root-project/root.git root_src && \
    mkdir root_build root_install && \
    cd root_build && \
    cmake -DCMAKE_INSTALL_PREFIX=/tools/root_install \
    -Dsoversion=ON  \
    -Dminimal=ON \
    -Denable-mathmore=ON \
    -Dbuiltin_gsl=ON \
    ../root_src && \
    cmake --build . --target install -- -j`nproc`


# test x11
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    x11-apps && \
    rm -rf /var/lib/apt/lists/*

# Switch to a non-root user
RUN chown -R ${USERNAME}:${USERNAME} /tools
RUN chmod -R u+rw /tools

# Set the XDG_RUNTIME_DIR environment variable
ENV XDG_RUNTIME_DIR="/run/user/${USERNAME}"

# add entrypoint script to source geant4 and root
RUN touch /tools/entrypoint.sh && \
    echo "#!/bin/bash" >> entrypoint.sh && \
    echo "source /tools/geant4-build-10/geant4make.sh" >> /tools/entrypoint.sh && \
    echo "source /tools/root_install/bin/thisroot.sh" >> /tools/entrypoint.sh && \
    echo "  exec \"\$@\"" >> /tools/entrypoint.sh && \
    chmod +x /tools/entrypoint.sh

# add it to bashrc too as that seems necessary sometimes
RUN echo "source /tools/geant4-build-10/geant4make.sh" >> /home/${USERNAME}/.bashrc && \
    echo "source /tools/root_install/bin/thisroot.sh" >> /home/${USERNAME}/.bashrc

USER ${USERNAME}:${USERNAME}

ENTRYPOINT ["/tools/entrypoint.sh"]
